### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by makapaka23** [Ne-Lexa/php-zip#11]
Just tried installing per `composer require nelexa/zip` (Mac) and got the error:

    - Installing nelexa/zip (3.1.3): Downloading (100%)         
    Failed to execute unzip -qq  '/Users/me/Sites/dashboard/vendor/nelexa/zip/63a7829a088c1c52214da04b998b47ea' -d '/Users/me/Sites/dashboard/vendor/composer/2815f4c5'

    error:  cannot create /Users/me/Sites/dashboard/vendor/composer/2815f4c5/Ne-Lexa-php-zip-171d4a8/tests/PhpZip/php-zip-ext-test-resources/bug40228?????????????????????????????????.zip
        Illegal byte sequence

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

It still seems to have done something - i can see nelexa in my vendor directory but this doesn't seem good ?

**Comment by Ne-Lexa** [comment]
Composer could not extract the file `tests/PhpZip/php-zip-ext-test-resources/bug40228私はガラスを食べられます.zip` using the `unzip` program.
Apparently a local problem. The file was deleted. It was a file from php-extension `php-zip` and did not represent a special value.

Update the package.
`composer update nelexa/zip`
