### ISSUE TITLE
Does this set password for NEW zip files

### ISSUE THREAD

**Issue by makapaka23** [Ne-Lexa/php-zip#12]
While I wait to hear back regarding another issue with composer installation, its unclear whether this package indeed can set a password for new zip files it creates ? I'm weary because the php ziparchive is unclear until you try it, that the setPassword method is only for extraction of an existing zip file that has a password, so I'd like to clear that up before I continue :)

**Comment by Ne-Lexa** [comment]
Yes, you can set a password for new files.
