### ISSUE TITLE
Simplest includes?

### ISSUE THREAD

**Issue by jcoonrod** [Ne-Lexa/php-zip#14]
I'm using this in GAE Standard environment as a simple git submodule - but I find I have to add about a zillion include statements to get it to work - is there a simpler way?

It works with a whole series of includes like:
$zpath="../php-zip/src/";
require($zpath."PhpZip/Util/CryptoUtil.php");
require($zpath."PhpZip/Util/FilesUtil.php");
...

But when I try something like:
set_include_path('../php-zip/src' . PATH_SEPARATOR . get_include_path());

I get Class 'PhpZip\ZipFile' not found

What do you suggest?

**Comment by Ne-Lexa** [comment]
Use the [`composer`](https://getcomposer.org/) or use the autoloader compatible with the [PSR-4 standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md).

**Comment by jcoonrod** [comment]
Thanks! GAE did not seem happy to work with an anonymous function, but it did with the following:

function zipautoload($class) {
	$file="../php-zip/src/".str_replace("\\","/",$class).".php";
	require $file;
}
spl_autoload_register("zipautoload");
