### ISSUE TITLE
"Too many open files" on macosx when trying to zip a folder with a huge amount of files

### ISSUE THREAD

**Issue by smoelker** [Ne-Lexa/php-zip#22]
I'm trying to zip a folder with a large amount of files and I get the following error:

`
vendor/nelexa/zip/src/PhpZip/Exception/InvalidArgumentException.php): failed to open stream: Too many open files in ...
`

It seems like all files are opened using fopen first and then all written to the archive instead of one by one.

**Comment by Ne-Lexa** [comment]
How many files are we talking about?
I tested adding 1 million files to the archive and did not encountered a problem.
Please tell us your OS, PHP version and problem code.
