### ISSUE TITLE
Error on adding files from string

### ISSUE THREAD

**Issue by chez14** [Ne-Lexa/php-zip#3]
Hi there, i was expecting to add files to a zip by a string, but it seems like it rejects the content, is it normal or something?

The error messages:
```
external file attributes out of range - mkdir.bat 
```

Here's my code:
```php
    public function generate(\Model\Ujian $ujian){
        $zip = new \PhpZip\ZipFile();
        $zipname = $this->tempFileGenerator(".zip");
        $this->zip = $zip;
        $ujian->peserta->orderBy('posisi asc');
        $this->ujian = $ujian;
        
        \F3::set("data.ujian", $ujian);
        $zip->addAll([
            'mkdir.bat' => \View\Bat::render("lab-mkdir.bat"),
            'copy.bat' => \View\Bat::render("lab-copy.bat"),
            'takeown.bat'=> \View\Bat::render("lab-takeown.bat")
            ]);
        $zip->saveAsFile($zipname);
        $zip->close();
            
        return $zipname;
    }
```
where `\View\Bat::render()` is a function that returns string.

**Comment by Ne-Lexa** [comment]
@chez14 , do you use a 32-bit version of php?
Try version 3.0.2.

**Comment by Ne-Lexa** [comment]
The error should no longer appear.
Use the latest version. Currently 3.1.0.

**Comment by chez14** [comment]
I've used other library, and i have no longer maintain those project, so i can't try out the latest version.

Thanks for updating, if the problem still persist, i'll reopen this issue.

Thanks bro! 😁
