### ISSUE TITLE
How to solve the problem of memory overflow when compressing large files

### ISSUE THREAD

**Issue by LianSchedule** [Ne-Lexa/php-zip#31]
**Description**  

When I tried to compress files close to 1G, there was a memory overflow error. My server memory is 16G, and I have ini_set ('memory_limit','8000M').
**Example**  

Fatal error: Out of memory (allocated 2097152) (tried to allocate 1004084008 bytes) in ...\vendor\nelexa\zip\src\PhpZip\Model\Entry\ZipNewFileEntry.php on line 51

**Comment by LianSchedule** [comment]
PHP Version 7.1.5
System | Windows NT PC-20180707XWVI 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
Zend Memory Manager | enabled
memory_limit | -1

**Comment by Ne-Lexa** [comment]
Hello.
The problem is clear.
What is the size of the added files?

**Comment by Ne-Lexa** [comment]
Fixed in 3.2.0 version

**Comment by anki7d** [comment]
1  gb
