### ISSUE TITLE
Error saving

### ISSUE THREAD

**Issue by i-panov** [Ne-Lexa/php-zip#33]
| Q                            | A
| -----------------------------| ---
| Library version(s) affected: | 3.1
| PHP version(s):              | 7.2
| OS (with bit depth):         | Debian 9 x86_64

**Description**  
I get an error when trying to save a file.

**How to reproduce**  
```
$zip = new ZipFile();
$zip->setCompressionLevel(ZipFileInterface::LEVEL_BEST_COMPRESSION);

foreach ($this->getFilesMapping() as $localName => $url) {
	try {
		$handle = fopen($url, 'r');
		$zip->addFromStream($handle, $localName, ZipFile::METHOD_DEFLATED);
	} finally {
		fclose($handle);
	}
}

$tmp = tempnam(sys_get_temp_dir(), '');
$zip->saveAsFile($tmp); // error is here
```

**Possible Solution**  
Maybe it's in the links? I am trying to add the `addFromStream` method with data by link. It looks like this library simply does not know how to work with links. :(

**Additional context**  
```
PHP Warning 'yii\base\ErrorException' with message 'mb_strlen() expects parameter 1 to be string, resource given'

in /var/www/html/vendor/nelexa/zip/src/PhpZip/Stream/ZipOutputStream.php:233

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'mb_strlen() exp...', '/var/www/html/v...', 233, Array)
#1 /var/www/html/vendor/nelexa/zip/src/PhpZip/Stream/ZipOutputStream.php(233): mb_strlen(Resource id #147)
#2 /var/www/html/vendor/nelexa/zip/src/PhpZip/Stream/ZipOutputStream.php(84): PhpZip\Stream\ZipOutputStream->entryCommitChangesAndReturnContent(Object(PhpZip\Model\Entry\ZipNewEntry))
#3 /var/www/html/vendor/nelexa/zip/src/PhpZip/Stream/ZipOutputStream.php(64): PhpZip\Stream\ZipOutputStream->writeEntry(Object(PhpZip\Model\Entry\ZipNewEntry))
#4 /var/www/html/vendor/nelexa/zip/src/PhpZip/ZipFile.php(1337): PhpZip\Stream\ZipOutputStream->writeZip()
#5 /var/www/html/vendor/nelexa/zip/src/PhpZip/ZipFile.php(1241): PhpZip\ZipFile->writeZipToStream(Resource id #337)
#6 /var/www/html/vendor/nelexa/zip/src/PhpZip/ZipFile.php(1217): PhpZip\ZipFile->saveAsStream(Resource id #337)
#7 /var/www/html/jobs/PublicationFilesJob.php(34): PhpZip\ZipFile->saveAsFile('/tmp/2U0eNF')
#8 /var/www/html/commands/TaskController.php(44): app\jobs\PublicationFilesJob->execute(Object(yii\queue\redis\Queue))
#9 [internal function]: app\commands\TaskController->actionTest()
#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('test', Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('test', Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('task/test', Array)
#15 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('task/test', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /var/www/html/yii(20): yii\base\Application->run()
#18 {main}
```

**Comment by Ne-Lexa** [comment]
You do not need to close the stream. It is read when it is saved and closed in the `$zip->close()` or  `__destruct()`.

```diff
-       try {
		$handle = fopen($url, 'r');
		$zip->addFromStream($handle, $localName, ZipFile::METHOD_DEFLATED);
-	} finally {
-		fclose($handle);
-	}
```

**Comment by i-panov** [comment]
Please help with another problem. The code is the same (only I, as you said, removed the call to `fclose`). I added a lot of files to the archive with this library. Under Windows 10 where I am developing an application, the archive has been created correctly. But when I launched the same on the script under Debian 9 - the archive was broken. The code did not change at all. The archive under Debian turned out to be also large (not empty), but the data in it is broken and not displayed by the archiver. Why it happens? I emphasize - under Windows with the same code, the archive is created not broken!

**Comment by Ne-Lexa** [comment]
@i-panov, I think php lacks internal memory. Try running the code in the console or increase the `memory_limit` in php.ini. I can not say more without logs or the resulting file.

PS: Кириллица поддерживается в ZIP записях и хранится в UTF-8.
Попробуйте проверить полученный файл в консоле:
```bash
unzip -t file.zip
```

**Comment by i-panov** [comment]
> Попробуйте проверить полученный файл в консоле:
О, вы говорите по русски? Отлично)) Архив действительно сломан:

```
$ unzip -t /media/sf_domains/test.zip 
Archive:  /media/sf_domains/test.zip
error:  expected central file header signature not found (file #2).
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
    testing: ????????/?????          
  error:  invalid compressed data to inflate
At least one error was detected in /media/sf_domains/test.zip.
```

> I think php lacks internal memory. Try running the code in the console or increase the `memory_limit` in php.ini. I can not say more without logs or the resulting file.
В смысле не хватает памяти? А как работает ваша библиотека? Она что создает архив в памяти? Просто я к тому что архив то может быть довольно большим и его нельзя создавать в памяти - так никакой оперативки не хватит. Если вы скажете какие логи вам нужны я постараюсь их найти.

**Comment by Ne-Lexa** [comment]
> В смысле не хватает памяти? А как работает ваша библиотека? Она что создает архив в памяти?

Основной кейс библиотеки как раз и есть работа в памяти. Например, взять существующий архив (шаблон), изменить содержимое, добавить новые файлы, подписи и т.п. и тут же не сохраняя на диск, отдать содержимое в браузер.
Данная библиотека решает мои бизнес задачи и может не охватывать все варианты использования, но я прислушиваюсь к её пользователям и в свободное время пилю новую версию в которой будет решён вопрос с памятью и улучшена производительность.
Всё же попробуйте увеличить `memory_limit` или запустить код в консольной команде, там `memory_limit` скорее всего будет -1. Сообщите, помогло ли вам это.

> Но под виндой все работает идеально... Странно это. У вас там какой-то платформо-зависимый код есть?

Нет, код не платформо-зависимый. Под windows даже не тестировался. 


Если вам нужно просто создать файл и сохранить его, лучшим решением будет воспользоваться [`\ZipArchive`](https://secure.php.net/ziparchive). Код на `C` будет работать быстрее и не будет занимать много памяти.

**Comment by i-panov** [comment]
> Всё же попробуйте увеличить `memory_limit` или запустить код в консольной команде, там `memory_limit` скорее всего будет -1. Сообщите, помогло ли вам это.

Не помогло. Да и я же вон пробовал добавить несколько легких файлов (меньше 1 мб) - такая же фигня.

> Если вам нужно просто создать файл и сохранить его, лучшим решением будет воспользоваться [`\ZipArchive`](https://secure.php.net/ziparchive). Код на `C` будет работать быстрее и не будет занимать много памяти.

Да, я с нее и начал. Просто честно говоря она не больно удобная... Ну например она не умеет добавлять данные из стрима, а мне надо добавлять файлы по ссылкам (как в примере выше). Таким образом используя ее у меня единственный выход - сохранять файлы на диск, потом добавлять в архив и удалять. Еще конечно она может из строки добавлять, но у меня попадались файлы которые просто не помещались в памяти. Поэтому я и решил поискать какие-то альтернативы... Ну видимо придется вернуться к ней.
