### ISSUE TITLE
Add tests folder to the .gitattributes file [Andr.Malware.Smsagent-6888392-0 FOUND]

### ISSUE THREAD

**Issue by VAMPIIRE** [Ne-Lexa/php-zip#34]
| Q                            | A
| -----------------------------| ---
| Library version(s) affected: | 3.1
| PHP version(s):              | 7.2
| OS (with bit depth):         |  Ubuntu 18.04 64-bit

**Description**  
ClamAV antivirus is saying that `/test/PhpZip/resources/test.apk` contain viruses. I don't know
why this file is needed there  <br>
Full error message: `"nelexa/zip/tests/PhpZip/resources/test.apk: Andr.Malware.Smsagent-6888392-0 FOUND"`

**How to reproduce**  
Install ClamAV malware tool on your machine and try to scan using it. 
Initially, I got this error when I've tried to upload this library to the hosting using cPanel.

**Possible Solution**  
It would be nice if you can add `.gitattribute` file with  `/tests export-ignore` line, which should remove this folder on the production.

**Comment by Ne-Lexa** [comment]
This is a false positive. This apk file is just "Hello World" for testing `zipalign`.
I will replace the file.

**Comment by VAMPIIRE** [comment]
Yep, I understand that file isn't dangerous, but I have a plugin which all clients are uploading thought cPanel and they are getting this error which brings me some problems :)

What about `.gitattribute`? It would be very nice if in production version all testing folders will be removed from the root folder of this package. 

Thanks for taking care of this file. I really appreciate it

**Comment by Ne-Lexa** [comment]
A `.gitattributes` file has been added.
Use version 3.1.11.
To install without a `tests/` folder use the command:

```bash
composer require nelexa/zip --prefer-dist
```
