### ISSUE TITLE
Cannot run another php command after $zipFile->outputAsAttachment ?

### ISSUE THREAD

**Issue by Taapo** [Ne-Lexa/php-zip#38]
When I try to run another command after $zipFile->outputAsAttachment -- it doesn't work, seems like $zipFile->outputAsAttachment creates an "exit" command?

**Comment by Taapo** [comment]
Just checked in the code - an exit is applied after the command. Isn't there a better way to do this? For example, I'm trying to clear up a temporary directory after creating the zip file, and now it's impossible to do so.

**Comment by Ne-Lexa** [comment]
The file is created in memory and after its creation you do not need to clean the temporary folder.

Use [ZipFile::outputAsString](https://github.com/Ne-Lexa/php-zip#Documentation-ZipFile-outputAsString) or [ZipFile::outputAsResponse](https://github.com/Ne-Lexa/php-zip#Documentation-ZipFile-outputAsResponse) if `ZipFile::outputAsAttachment` is not suitable.

**Comment by Taapo** [comment]
Heya, I think I miscommunicated. This is what I mean:
* I need to pull files from an external source (S3) to my server - into a temporary directory
* Then I create a zip file using your library, works perfect
* I use outputAsAttachment as I want to download it
* Afterwards (in same script) I want to delete the directory I temporarily created for the downloaded s3 files
* since the outputAsAttachment function ends with exit() ... I cannot put anything after I call the zip function ...

Am I missing something? Maybe I misunderstand.

PS. When I comment exit() in the function, it functions like it should ...

**Comment by Ne-Lexa** [comment]
You can simply extend the class.

Example:
```php
<?php
declare(strict_types=1);

use PhpZip\Exception\ZipException;

require __DIR__ . '/vendor/autoload.php';

class ZipFile extends \PhpZip\ZipFile
{
    /**
     * Output .ZIP archive as attachment.
     *
     * @param string $outputFilename Output filename
     * @param string $mimeType Mime-Type
     * @param bool $attachment Http Header 'Content-Disposition' if true then attachment otherwise inline
     * @throws ZipException
     */
    public function outputAttachment(string $outputFilename, string $mimeType = 'application/zip', bool $attachment = true): void
    {
        $content = $this->outputAsString();
        $this->close();

        $headerContentDisposition = 'Content-Disposition: ' . ($attachment ? 'attachment' : 'inline');
        if (!empty($outputFilename)) {
            $headerContentDisposition .= '; filename="' . basename($outputFilename) . '"';
        }

        header($headerContentDisposition);
        header('Content-Type: ' . $mimeType);
        header('Content-Length: ' . strlen($content));
        echo $content;
    }
}

$file = sys_get_temp_dir().'/_temp_file_1.txt';
$file2 = sys_get_temp_dir().'/_temp_file_2.txt';

file_put_contents($file, random_bytes(1024));
file_put_contents($file2, random_bytes(1024));

$zipFile = new ZipFile();
try {
    $zipFile->addFile($file, 'file.txt');
    $zipFile->addFile($file2, 'file2.txt');
    $zipFile->outputAttachment('file.zip');
} finally {
    unlink($file);
    unlink($file2);
}

```

**Comment by Taapo** [comment]
Nice,  thanks a lot. I'll try that soon!
