### ISSUE TITLE
ZIP Slip vulnerability

### ISSUE THREAD

**Issue by kukuxumushi** [Ne-Lexa/php-zip#39]
| Q                            | A
| -----------------------------| ---
| Library version(s) affected: | 3.1.11 and earlier

**Description**  

Attackers can create Zip archives that use path traversal to overwrite important files on affected systems, destroying them or replacing them with malicious alternatives or upload a new one with a malicious code.
**How to reproduce**  

1) Create file with some code, for example:
```
<?php
phpinfo();
?>
```
2) Name it somehow like this "xxxphpinfo.php".
3) Create a zip archive.
4) Open zip archive in hex editor. Change xxx to ../ in two places: in the top of the hex and in the bottom.
5) Pass modified archive to the Ne-Lexa/php-zip extraction function. For example:
```
$zipFile = new \PhpZip\ZipFile();
$zipFile->openFile('xxxphpinfo.zip');
$zipFile->extractTo(uploads/zips/);
```
6) Navigate to uploads and execute phpinfo.php.

**Possible Solution**  

Use php zlib or somehow escape ../ characters.
**Additional context**  

https://snyk.io/research/zip-slip-vulnerability
[xxxphp1.zip](https://github.com/Ne-Lexa/php-zip/files/3432560/xxxphp1.zip)

**Comment by Ne-Lexa** [comment]
Hello. Thanks for the issue.
Fixed a vulnerability.
Update library version:
`composer update nelexa/zip`

Now extracting from the archive works the same as in `unzip`.
`../path1/path2/./../path3/../../../file.ext` => `path1/path2/path3/file.ext`
