### ISSUE TITLE
count() returns 0 when files are added in directories

### ISSUE THREAD

**Issue by st0at** [Ne-Lexa/php-zip#4]
if all files are added like

$zip_file->addFile(
    $file_path,
    $directory_name . '/' . $file_name_in_archive
);

$zip_file->count() or count($zip_file) returns 0

**Comment by Ne-Lexa** [comment]
`count ()` contains the number of records from the open (input stream) of the archive.
Changes made to the memory without saving the file do not affect the information about the opened or newly created archive.
See Example: https://github.com/Ne-Lexa/php-zip/blob/master/tests/PhpZip/ZipFileTest.php#L99

In the future this behavior can be changed.

If you need this functionality, look at the previous version 2 (https://github.com/Ne-Lexa/php-zip/tree/2.2.0) in it the input and output stream is divided.

**Comment by st0at** [comment]
How can I get count of added files which were added with addFile() function?

**Comment by Ne-Lexa** [comment]
The library version has been updated, and this behavior has been changed.

Now you will always know the actual number of entries (`ZipFile::count()`) in the archive and the current file list (`ZipFile::getListFiles()`).

Use the latest version. Now this is 3.1.0.

**Comment by st0at** [comment]
Thank you!
