### ISSUE TITLE
get chinese zip error

### ISSUE THREAD

**Issue by hanfeicode** [Ne-Lexa/php-zip#40]
i use  Bandizip 、360zip
all can not get the right zip list name in chinese

like:
360zip2/360zip/1572502882678.jpg
360zip2/360zip/2020年/   utf8
360zip2/360zip/2020年/1572502882678.jpg   utf8
360zip2/360zip/2020年/QQ浏览器截图20191102102552.png   utf8
360zip2/360zip/ICP备案信息登记表.doc   utf8
360zip2/360zip/QQ浏览器截图20191102102552.png   utf8
360zip2/360zip/域名授权书.doc   utf8
360zip2/360zip/域名证书.png   utf8
360zip2/360zip/备案材料准备举例.png   utf8
360zip2/360zip/备案流程.docx   utf8

**Comment by Ne-Lexa** [comment]
I don't understand your problem.
Attach the problem file.

**Comment by kasuganosoras** [comment]
用 bandizip 随便压缩了一个文件没发现问题，乱码可能是因为你压缩用的编码不是 UTF-8，我记得 Bandizip 有设置可以开启 Zip 文件压缩 UTF-8 编码的。

**Comment by Ne-Lexa** [comment]
The library uses UTF-8.

```php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$entries = [
    '360zip2/360zip/1572502882678.jpg' => 'test',
    '360zip2/360zip/2020年/1572502882678.jpg' => 'test',
    '360zip2/360zip/2020年/QQ浏览器截图20191102102552.png' => 'test',
    '360zip2/360zip/ICP备案信息登记表.doc' => 'test',
    '360zip2/360zip/QQ浏览器截图20191102102552.png' => 'test',
    '360zip2/360zip/域名授权书.doc' => 'test',
    '360zip2/360zip/域名证书.png' => 'test',
    '360zip2/360zip/备案材料准备举例.png' => 'test',
    '360zip2/360zip/备案流程.docx' => 'test',
];

$zipFile = new \PhpZip\ZipFile();
$zipFile->addAll($entries);
$zipFile->saveAsFile('chinese.zip');
$zipFile->close();

$zipFile->openFile('chinese.zip');

foreach ($zipFile as $entryName => $contents) {
    if ($entries[$entryName] !== $contents) {
        throw new \RuntimeException('Bad archive.');
    }
}
$zipFile->close();

```

![image_2020-01-13_10-31-39](https://user-images.githubusercontent.com/17830391/72238964-75066d00-35f0-11ea-8ec1-a52dba0c1f2b.png)

You can also set charset when opening files if the file names are encoded in a different encoding.
Example.
```php
$zipFile->openFile('file.zip', [
    'charset' => 'cp936',
]);
```

Attach the problematic zip file and php code to solve your problem.

**Comment by know-that** [comment]
@Ne-Lexa Try adding the Chinese zip package with rar suffix to zipFile,This will cause the name to be garbled。

**Comment by know-that** [comment]
> @Ne-Lexa Try adding the Chinese zip package with rar suffix to zipFile,This will cause the name to be garbled。

In this case, rar compressed in Windows Environment
