### ISSUE TITLE
Cannot open zips with unarchiver in Mac OS Catalina

### ISSUE THREAD

**Issue by MagneticI** [Ne-Lexa/php-zip#41]
I am not able to open zips greater than 4GB that have been generated with this library. 

Receiving the below error when attempting to unzip from finder
![image](https://user-images.githubusercontent.com/10122443/68606825-4697d480-047d-11ea-8758-c57b46c037ea.png)

Receiving the below error when attempting to unzip from the command line:
`Archive:  BakersBigCatalinaWineMixerZip.zip
  inflating: 09_ProPresenterFiles/04_Preteen/1910 Preteen.pro6plx
  inflating: 09_ProPresenterFiles/02_K3/1910 K3.pro6plx
  inflating: 09_ProPresenterFiles/03_K5Plus/1910 K5Plus.pro6plx
file #4:  bad zipfile offset (local header sig):  2632229990`

When looking at the detailed information on the zip, I see that the text below displays for the failing file. 
`There are an extra -4294967280 bytes preceding this file.`

Again this only happens on Mac's latest OS. No issues otherwise.

**Comment by Ne-Lexa** [comment]
Fixed in 3.2.0 version
