### ISSUE TITLE
DirectoryIterator error

### ISSUE THREAD

**Issue by ifeiwu** [Ne-Lexa/php-zip#43]
$ignoreFiles = [
    '!backup/'
];
            
$directoryIterator = new \DirectoryIterator(ROOT_PATH);
 
$ignoreIterator = new \PhpZip\Util\Iterator\IgnoreFilesRecursiveFilterIterator(
    $directoryIterator, 
    $ignoreFiles
);
            
$zipFile
        ->addFilesFromIterator($ignoreIterator)
        ->saveAsFile($zippath)
        ->close();

------------------------------------------------

[23-Jan-2020 16:52:51 PRC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpZip\Util\Iterator\IgnoreFilesRecursiveFilterIterator::__construct() must implement interface RecursiveIterator, instance of DirectoryIterator given, called in /home/wwwroot/xxx.com/admin/backup.php on line 34 and defined in /home/wwwroot/xxx.com/vendor/nelexa/zip/src/Util/Iterator/IgnoreFilesRecursiveFilterIterator.php:26
Stack trace:
#0 /home/wwwroot/xxx.com/admin/backup.php(34): PhpZip\Util\Iterator\IgnoreFilesRecursiveFilterIterator->__construct(Object(DirectoryIterator), Array)
#1 /home/wwwroot/xxx.com/admin/restler.php(2): Backup->getSite()
#2 /home/wwwroot/xxx.com/admin/api.php(56): Restler->handle()
#3 {main}
  thrown in /home/wwwroot/xxx.com/vendor/nelexa/zip/src/Util/Iterator/IgnoreFilesRecursiveFilterIterator.php on line 26

**Comment by Ne-Lexa** [comment]
This code works fine on the latest version of the library. 
Check if you are creating the `$directoryIterator` variable correctly. You are passing a non-recursive iterator.

Run this code for the test:
```php
<?php

// save to test-zip.php

require __DIR__ . '/vendor/autoload.php';

$ignoreFiles = [
    '.git',
    'vendor/',
    '!backup/',
];

$directoryIterator = new \RecursiveDirectoryIterator(__DIR__);

$ignoreIterator = new \PhpZip\Util\Iterator\IgnoreFilesRecursiveFilterIterator(
    $directoryIterator,
    $ignoreFiles
);

$zipFile = new \PhpZip\ZipFile();
$zipFile
    ->addFilesFromIterator($ignoreIterator)
    ->saveAsFile(__DIR__ . '/test.zip')
    ->close()
;

```
and run
```bash
php test-zip.php
```

P.S.: The best way to add files right now is Symfony Finder.
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$directory = __DIR__;

$finder = (new \Symfony\Component\Finder\Finder())
    ->exclude('!backup')
    ->exclude('.git')
    ->exclude('vendor/')
    ->in($directory)
;

$zipFile = (new \PhpZip\ZipFile());
$zipFile->addFromFinder($finder);
$zipFile->saveAsFile('backup.zip');
$zipFile->close();

```

**Comment by ifeiwu** [comment]
I'm sorry. I wrote the code wrong. I fixed it. I'm using your new method

This mistake
$directoryIterator = new \DirectoryIterator(ROOT_PATH);
