### ISSUE TITLE
password not applying to archive

### ISSUE THREAD

**Issue by sticcino** [Ne-Lexa/php-zip#44]
| Q                            | A
| -----------------------------| ---
| Library version(s) affected: | x.y.z
| PHP version(s):              | 7.2
| OS (with bit depth):         | Windows 10

also experiencing same issue with password, you attempt to set it, no errors archive is created, but not password protected.

**Comment by Ne-Lexa** [comment]
Write a sample code to demonstrate the error.

**Comment by sticcino** [comment]
Hi,

all functions work good, just no pwd applied

$zipFile = new \PhpZip\ZipFile();
$encryptionMethod = \PhpZip\Constants\ZipEncryptionMethod::WINZIP_AES_256;
                                                 
	$mimeType = 'application/zip';
	$globPattern = '**.{pdf}'; // glob pattern -> add all.pdf files
    $password = _getClientInfo("encryption_key", $sAccountId);        

	try {
		$zipFile
		->addFilesFromGlob("$documentPath", $globPattern)
		->saveAsFile("$outputFilename") // save the archive to a file
        ->setPassword($password, $encryptionMethod)
		->close(); // close archive            
	}

**Comment by Ne-Lexa** [comment]
First you need to call setPassword, and then saveAsFile.

**Comment by sticcino** [comment]
Hi,

thanks for you help. I still can't get it working. debugging i look at the zipFile->Entries, the password is set for each file, but still the container zip file is not protected and can be opened.

$zipFile->zipContainer->entries['abc.pdf']->password ==> 12345
$zipFile->zipContainer->entries['def.xls']->password ==> 12345

i tried the setPassword at different stages, with the same outcome

	// create new archive
	//
	$mimeType = 'application/zip';
        $globPattern = '**.{jpg,jpeg,png,xls,xlsx,doc,docx,pdf}'; // glob pattern
        $password = "12345";       

    $zipFile = new \PhpZip\ZipFile();    
    $encryptionMethod = \PhpZip\Constants\ZipEncryptionMethod::WINZIP_AES_256;                                                 

===> HERE <===
    $zipFile->setPassword($password, $encryptionMethod);        
    
	try {
		$zipFile
		->addFilesFromGlob("$documentPath", $globPattern)
==>HERE                ->setPassword($password, $encryptionMethod)
		->saveAsFile("$outputFilename");
                $zipFile->close();
	}

**Comment by sticcino** [comment]
Hi,
got it working, thank you. installed winZip archiver app to tes and prompting for password.
only change I made was encapsulating $password as "$password"

Final Code:

    $mimeType = 'application/zip';
    $globPattern = '**.{jpg,jpeg,png,xls,xlsx,doc,docx,pdf}'; // glob pattern
    $password = _getClientInfo("encryption_key", $sAccountId); 

    $zipFile = new \PhpZip\ZipFile();    
    $encryptionMethod = \PhpZip\Constants\ZipEncryptionMethod::WINZIP_AES_256;                                                 
    
	try {
		$zipFile
		->addFilesFromGlob("$documentPath", $globPattern)
               ->setPassword("$password", $encryptionMethod)
	       ->saveAsFile("$outputFilename");
        $zipFile->close();
	}

**Comment by Ne-Lexa** [comment]
I'm glad it worked out for you.
