### ISSUE TITLE
CRC32 checks fails on 32bit platforms

### ISSUE THREAD

**Issue by mijohansen** [Ne-Lexa/php-zip#5]
First of all, ty for creating this great library. It almost fixes an error that have been haunting Google App Engine for PHP since the beginning, ref this issue: https://issuetracker.google.com/issues/35897760

Anyway. It seems like the crc32() function in PHP doesn't behave equal on 32-bit platforms, and apparently Google App Engine is running 32-bit(!). I have disabled the CRC32 checks in my tests and it seems to work. But I guess its a reason for doing those checks.

**Comment by Ne-Lexa** [comment]
In `composer.json`, the dependence on 64-bit is directly defined.
On the 32-bit platform was not tested.
```json
{
...
     "require": {
         "php-64bit": "^ 5.5 || ^ 7.0"
     }
...
}
```
However, describe your problem, attach stacktrace.
Write what CRC is expected and what the library calculates.
If possible, attach a problem file / code.

**Comment by mijohansen** [comment]
Sorry about a not very presise feedback there. I have created a small test that displays the issue. This should be possible to reproduce:

```php
<?php
require_once 'vendor/autoload.php';

use PhpZip\ZipFile;

header("Content-Type: text/plain");
$test_file_loc = "https://www.colorado.edu/conflict/peace/download/peace.zip";
$test_temp_file = tempnam(sys_get_temp_dir(), "test_temp_file");
$fp = fopen($test_temp_file, 'w');
fwrite($fp, file_get_contents($test_file_loc));
fclose($fp);
echo "Filename......: " . $test_file_loc . PHP_EOL;
echo "Tempname......: " . $test_temp_file . PHP_EOL;
echo "CRC32.........: " . crc32(file_get_contents($test_temp_file)) . PHP_EOL;
echo "Filesize......: " . filesize($test_temp_file) . PHP_EOL;
echo "PHP_INT_SIZE..: " . PHP_INT_SIZE . PHP_EOL;
try {
    $zip = new ZipFile();
    $zip->openFile($test_temp_file);
    print_r($zip->getListFiles());
} catch (Exception $exception) {
    echo "ErrorMessage: ".print_r($exception->getMessage(),1);
}
```

This will yield the following result on a 64-bit platform:
```
Filename......: https://www.colorado.edu/conflict/peace/download/peace.zip
Tempname......: vfs://root/temp/test_temp_file59f762ff750e73.68493181
CRC32.........: 1488766247
Filesize......: 627874
PHP_INT_SIZE..: 8
Array
(
    [0] => !core_problems.htm
    [1] => !overlay_problems.htm
```

However, when moving to the 32bit Google App Engine platform I get the following result:
```
Filename......: https://www.colorado.edu/conflict/peace/download/peace.zip
Tempname......: vfs://root/temp/test_temp_file59f7630adc5329.80889221
CRC32.........: 1488766247
Filesize......: 627874
PHP_INT_SIZE..: 4
ErrorMessage: CRC-32 out of range - !core_problems.htm
```

Hope this help debugging the issue. The issue is also described there: http://php.net/manual/en/function.crc32.php

**Comment by Ne-Lexa** [comment]
@mijohansen, check on version 3.0.2.
For the 32-bit version, not all functionality is available, but the code above should work.

**Comment by mijohansen** [comment]
Forgot to answer this. Thank you very much! The few developers having this problem on Google App Engine will probably send their love to this library. :-D

**Comment by Ne-Lexa** [comment]
A new version of the library 3.1.0 has been released.
In it, many changes were made to ensure that it worked correctly with the 32-bit version of php. The only thing that does not work yet is the encryption of records using the `Traditional PKWARE Encryption` method.

I would be grateful for feedback, whether everything is all right.
