### ISSUE TITLE
php-zip does not support unicode folder names

### ISSUE THREAD

**Issue by praine** [Ne-Lexa/php-zip#52]
**Description**  
I'm trying to use $zipFile->addEmptyDir() with Japanese text and the text does not appear in the directory name

**How to reproduce**  
$zipFile->addEmptyDir('こんにちは')

**Comment by Ne-Lexa** [comment]
Hello.
I did not find a problem with this.
Give more context.

```php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$zipFile = new \PhpZip\ZipFile();
$zipFile->addEmptyDir('こんにちは');
$zipFile->saveAsFile(__DIR__ . '/test.zip');
$zipFile->close();
```

Result:
![Screenshot](https://user-images.githubusercontent.com/17830391/80064446-be941b80-8540-11ea-8651-80a065772c8c.png)
[test.zip](https://github.com/Ne-Lexa/php-zip/files/4520512/test.zip)
