### ISSUE TITLE
Is it possible to use this repo without composer? Basically I want to convert the whole library into one php script. Is it possible? 

### ISSUE THREAD

**Issue by apurbajnu** [Ne-Lexa/php-zip#55]
Is it possible to use this repo without composer? Basically I want to convert the whole library into one php script. Is it possible?

**Comment by Ne-Lexa** [comment]
To use the library without a composer, you must use a [PSR-4 compatible autoloader](https://www.php-fig.org/psr/psr-4/examples/).

For packing in one file, the best option would be to pack in Phar archive.
