### ISSUE TITLE
Can't setPassword on PHP 5.6

### ISSUE THREAD

**Issue by byungjikroh** [Ne-Lexa/php-zip#56]
| Q                            | A
| -----------------------------| ---
| Library version(s) affected: | 3.3.0
| PHP version(s):              | 5.6.40
| OS (with bit depth):         | macOS Catalina 10.15.4

**Description**  

There is an error to set password under PHP 7 because it uses 'random_bytes' which is add in PHP 7

**How to reproduce**  

$zipFile->setPassword('password')

**Possible Solution**  

Use the depreciated 'randomBytes' function in src/Util/CryptoUtil.php for under PHP 7

**Additional context**  

<b>Fatal error</b>:  Call to undefined function PhpZip\IO\Filter\Cipher\WinZipAes\random_bytes() in <b>/Applications/XAMPP/xamppfiles/htdocs/thecallcokr/vendor/nelexa/zip/src/IO/Filter/Cipher/WinZipAes/WinZipAesEncryptionStreamFilter.php</b> on line <b>104</b><br />

**Comment by Ne-Lexa** [comment]
Hello.
The library [uses](https://github.com/Ne-Lexa/php-zip/blob/master/composer.json#L27) the polyfill package "paragonie/random_compat".
Check your composer.json file and the "replace" section for possible removal of the "paragonie/ andom_compat" library from the dependencies.

**Comment by byungjikroh** [comment]
Thanks. 

There was no "replace" section on composer.json. 
But I added "paragonie/ andom_compat" manullay with 'composer require paragonie/random_compat:\<9.99' and it is resolved.
