### ISSUE TITLE
Virgula a mais nas linhas 85 e 95 no arquivo /.phpstorm.meta.php

### ISSUE THREAD

**Issue by nextstage-brasil** [Ne-Lexa/php-zip#58]
| Q                            | A
| -----------------------------| ---
| Library version(s) affected: | x.y.z
| PHP version(s):              | x.y.z
| OS (with bit depth):         | 

**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by Ne-Lexa** [comment]
An extra comma is not an error.

**Comment by Araqel** [comment]
@Ne-Lexa it is an error for wp.org , we cannot upload our plugin to wp.org which uses your package , could you please fix?

**Comment by Ne-Lexa** [comment]
@Araqel ok.
Version 3.3.2 released.

**Comment by Araqel** [comment]
Thx !!!
