### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by stevedesmond-ca** [Ne-Lexa/php-zip#72]
**Description**  
As a developer using this library, I want to upgrade my app to PHP 8, so I can keep up with the latest patches.

**Example**  
Currently, composer fails with
```
  Problem 1
    - nelexa/zip is locked to version 3.3.3 and an update of this package was not requested.
    - nelexa/zip 3.3.3 requires php ^5.5.9 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
```
Not sure if any code needs to be changed beyond the composer config

**Comment by odan** [comment]
I think more changes are needed:

* The extension `mcrypt` is deprecated since PHP 7.1 and should be replaced with `openssl`

PHP 8 compatibility check result:

```php
FILE: php-zip/src/Util/CryptoUtil.php
----------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 48 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and
    |       | removed since PHP 7.2; Use openssl (preferred) or
    |       | pecl/mcrypt once available instead
 48 | ERROR | Function mcrypt_decrypt() is deprecated since PHP 7.1
    |       | and removed since PHP 7.2; Use OpenSSL instead
 48 | ERROR | The constant "MCRYPT_RIJNDAEL_128" is deprecated since
    |       | PHP 7.1 and removed since PHP 7.2
 72 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and
    |       | removed since PHP 7.2; Use openssl (preferred) or
    |       | pecl/mcrypt once available instead
 72 | ERROR | Function mcrypt_encrypt() is deprecated since PHP 7.1
    |       | and removed since PHP 7.2; Use OpenSSL instead
 72 | ERROR | The constant "MCRYPT_RIJNDAEL_128" is deprecated since
    |       | PHP 7.1 and removed since PHP 7.2
----------------------------------------------------------------------
```

* Implement phpunit 9.3 which supports PHP 7.3+: https://phpunit.de/supported-versions.html
* Some tests must be updated for phpunit
  * Change `$this->setExpectedException(...)` to `$this->expectException(...)`
  * Add `: void` as return type
* Drop support for PHP less than 7.3

**Comment by giansalex** [comment]
@odan , but for i can install this package with composer + php 8.0, is only neccesary `|| ^8.0`.
I prefer this constraint like symfony packages
```json
{
    "php": ">=7.2.5"
}
```

**Comment by Ne-Lexa** [comment]
Version 4.0 has been released with PHP 8 support.
Thank you for your contribution.
