### ISSUE TITLE
Error if the file is empty

### ISSUE THREAD

**Issue by visavi** [Ne-Lexa/php-zip#8]
> Get entry contents.
> 
> // $entryName = 'path/to/example-entry-name.txt';
> 
> $contents = $zipFile[$entryName];
> Checks whether a entry exists.
> 
> // $entryName = 'path/to/example-entry-name.txt';
> 
> $hasEntry = isset($zipFile[$entryName]);
> 

if the file exists, but it is empty (0 bytes), then an error is displayed
ErrorException (E_WARNING)
fread (): Length parameter must be greater than 0

I think this is not correct, since the file can be empty in the archive

**Comment by Ne-Lexa** [comment]
This is a bug, and it has already been resolved in the forthcoming release of version 3.1.0, as well as much more. In addition, version 3.0.3 will be released with the closure of this error.

**Comment by Ne-Lexa** [comment]
Bug fixed. Upgrade to version 3.0.3.

**Comment by visavi** [comment]
Тут тоже   https://github.com/Ne-Lexa/php-zip/blob/42c0fc59dff30e32630455e9e645c63358e013ac/src/PhpZip/ZipFile.php#L1047
если файл пустой  выкидывает exception, хотя может так и надо

кстати не хватает функционала Content-Disposition: inline;  чтобы не скачивало, а выводило в браузере

**Comment by Ne-Lexa** [comment]
> если файл пустой выкидывает exception, хотя может так и надо
Так и надо. Хотя HTTP спецификация не запрещает, поэтому в следующей версии будет поддержка пустого имени файла для сохранения

> кстати не хватает функционала Content-Disposition: inline; чтобы не скачивало, а выводило в браузере
Будет в следующей версии.

**Comment by Ne-Lexa** [comment]
Вышел релиз 3.1.0, в котором, среди прочего, добален недостающий функционал с Content-Disposition: inline.
