### ISSUE TITLE
encryption doesn't work

### ISSUE THREAD

**Issue by CharleysTante** [Ne-Lexa/php-zip#9]
I can add string content into a zip archiv and save it as file, but if I use the methode "setPassword" I'll get only something like this: codes.zip.temp5a217f32d88d8

However, this error happens only if I use contents bigger then 700 Bytes. Without encryption it works fine.

**Comment by Ne-Lexa** [comment]
Hello.
Which encryption method was used?
AES or Traditional?

Report the library version, the operating system, the version and the bit depth of PHP.

Were there any errors? Show stacktrace and an example of PHP code.

**Comment by CharleysTante** [comment]
Hello,

Thanks for the quick reaktion :)

Version: 3.1.2
OS: Windows 7
PHP: 7.0.13, 32 Bit
Encryption: AES

No, there were no errors displayd. And as I said, with, eg. 10 Byte content, I recieved a correct built archiv. Here the code:

/**
 * https://github.com/Ne-Lexa/php-zip
 *
 * @param string $path complete with file name
 * @param string $content
 * @param string $pwd
 */
public function zipStorage($path, $content, $pwd)
{
    $encryptMethod = \PhpZip\ZipFile::ENCRYPTION_METHOD_WINZIP_AES_256;
    $zipFile = new \PhpZip\ZipFile();
    $zipFile
    ->addFromString('codes.csv', $content)
    ->setPassword($pwd, $encryptMethod)
    ->saveAsFile($path)
    ->close();
}

**Comment by CharleysTante** [comment]
Hello,

Today I've tested your library under the following conditions with the same code again:

Version: 3.1.2
OS: CentOS 7.3.1611, 64 Bit
PHP: 7.0.22, 64 Bit
Modules: OpenSSL with aes-256-ctr and b2
Encryption: AES

However, exactly the same result I get something like this 'codes.zip.temp5a25639d9d686' and no error messages :-(

**Comment by Ne-Lexa** [comment]
php-error.log looked?

**Comment by CharleysTante** [comment]
OK, I had a look at the log file, here the result:

PHP Fatal error:  Uncaught PhpZip\\Exception\\ZipException: codes.csv (unsupported compression method 65535) in /vendor/nelexa/zip/src/PhpZip/Stream/ZipOutputStream.php:314\nStack trace:\n#0
/vendor/nelexa/zip/src/PhpZip/Stream/ZipOutputStream.php(83): PhpZip\\Stream\\ZipOutputStream->entryCommitChangesAndReturnContent(Object(PhpZip\\Model\\Entry\\ZipNewEntry))\n#1
/vendor/nelexa/zip/src/PhpZip/Stream/ZipOutputStream.php(63): PhpZip\\Stream\\ZipOutputStream->writeEntry(Object(PhpZip\\Model\\Entry\\ZipNewEntry))\n#2
/vendor/nelexa/zip/src/PhpZip/ZipFile.php(1315): PhpZip\\Stream\\ZipOutputStream->writeZip()\n#3
/vendor/nelexa/zip/src/PhpZip/ZipFile.php(1222): PhpZip\\ZipFile->writeZipToStream(Resource id #4)\n#4
/vendor/nelexa/zip/src/PhpZip/ in vendor/nelexa/zip/src/PhpZip/Stream/ZipOutputStream.php on line 314,

**Comment by CharleysTante** [comment]
Thanks a lot, it works great, tested with CentOS :-)

**Comment by Ne-Lexa** [comment]
Thanks for the ticket.
Upgrade to 3.1.3 with composer.
```composer update nelexa/zip```
