### ISSUE TITLE
Empty PSR-7 ZIP-File in body stream

### ISSUE THREAD

**Issue by odan** [Ne-Lexa/php-zip#91]
| Q                            | A
| -----------------------------| ---
| Library version(s) affected: | 4.0.2
| PHP version(s):              | 8.1.6
| OS (with bit depth):         | Windows 10 64-bit

**Description**  

When I try to output a ZIP-File as PSR-7 response, the ZIP file is valid, but contains no files.
I use the existing nyholm/psr7 response object.

**How to reproduce**  

```php
$zipFilename = sprintf('%s.zip', tempnam(sys_get_temp_dir(), 'test'));

$zip = new \PhpZip\ZipFile();
$zip = $zip->addFromString('file.txt', 'File content');
$zip = $zip->saveAsFile($zipFilename);
$zip->close();

$realContent = file_get_contents($zipFilename);

// $response = new \Nyholm\Psr7\Response();
$response = $zip->outputAsPsr7Response($response, 'test.zip');

$bodyContent = (string)$response->getBody();

echo strlen($realContent) . "\n";  // 126 bytes
echo strlen($bodyContent) . "\n"; // 22 bytes

if ($bodyContent !== $realContent) {
    echo 'Invalid ZIP content';
    exit;
}

return $response;
```

**Possible Solution**  

**Additional context**

**Comment by Ne-Lexa** [comment]
@odan you use the PSR7 response incorrectly.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

try {
    $zip = new \PhpZip\ZipFile();
    $zip = $zip->addFromString('file.txt', 'File content');
    $response = $zip->outputAsPsr7Response(new \Nyholm\Psr7\Response(), 'test.zip');

    $bodyContent = (string)$response->getBody();

    echo strlen($bodyContent) . "\n"; // 126 bytes
} finally {
    $zip->close();
}

```

**Comment by odan** [comment]
Hi @Ne-Lexa Thank's for the quick answer.

It was not how I use the response object. 
The actual issue was to invoke the `$zip->close();` method.

Without closing the file, the response object is valid now. Thanks.
